services:
  devcontainer:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
      - vscode-server:/root/.vscode-server
    command: sleep infinity
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=gemma3n:e4b
      - OLLAMA_FORMAT_PATH=format/generate.schema.json

volumes:
  vscode-server:
